### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by fengyangyang98** [git-yueyi/regex2nfa#1]
请问一下运行哪一个文件才能够得到你所提供的示例输出呢？

请问 C 版本的如何遍历才能够得到类似于示例的输出？

**Comment by git-yueyi** [comment]
1.运行 com.yueyi.laxter.App.java
2.C版本遍历逻辑是一样的，也是从头至尾。只是他的程序和数据结构更巧妙，需要先看懂。
